### ISSUE TITLE
Snapshot confirmation dialog model is not user friendly

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-snapshots#13]
During QA, this was reported:

_Test steps_
1. Navigate to site and login as admin
2. View home page and click Customize to navigate to Customizer 
3. Make a change (ie. to the logo) in customizer and click [save]
4. View Save Dialog Box 

_Expected_
The user will be able to easily preview and save a ‘draft’ of their edits and understand the options

_Actual_
On clicking to ‘Save’ the changes in customizer a dialog displays with 2 options for Preview scope:
(.) diff - Previews the dirty settings
( ) full - Previews all the settings        

It is not clear to me (or I suspect most users) what those options mean? Is a choice required here and if not, why give the user the choice?

**Comment by westonruter** [comment]
See also #12 for a UI for listing snapshots in the admin. There could also be a UI in the Customizer to save/load snapshots in a similar way that the [Settings Revisions](https://wordpress.org/plugins/settings-revisions/) plugin [prototyped](https://wordpress.org/plugins/settings-revisions/screenshots/).

**Comment by alcurrie** [comment]
Based on the test steps and results above I have some suggestions that may improve usability:
_Before clicking to Save_
- Change the button from [Save] which is more generic  and make it more specific [Save Snapshot]
- Add a brief explanation of what the button will do and what a Snapshot is.  I'd recommend moving the current user explanation from inside the Save dialog box i.e. ‘Clicking “Save” will create a new snapshot’ as a good starting point for a user instruction if that instruction was moved from appearing inside the dialog box to appear as an user explanation for the save button. 

_Once user has clicked to Save and the Dialog Box appears_
- **Rename the dialog Save Snapshot**
- **Clarify the User Instruction** - The current user explanation from the Save dialog box is ‘Clicking “Save” will create a new snapshot.’ As noted I think the more general explanation would work better before the user clicks save. On the dialog box, I’d recommend more specific user instruction ie. something like  ‘Clicking save will save a snapshot of  the current state of your page/post without publishing your changes to the live site. Save or bookmark the snapshot URL to return to the page and continue your edits.’
- **Consider changing the label ‘Preview Scope’ to ‘Snapshot Scope’.** I think the term ‘Preview’ is more general and also applies to what appears in the main window, and the ‘Snapshot’ is more specific.
- **Scope Options diff or full**\- I’d recommend clarifying the options. I don’t think the term diff or full will be clear to the average user.  Maybe provide scope options based on user process ie. page/post content only or include all customizer site settings.  
- Instead of offering 2 options, **consider defaulting to a limited option** ie. previewing only the specific page or posts settings with the 'Advanced' option of including all customizer site settings

**Comment by westonruter** [comment]
Instead of “Save Snapshot” the button could be just “Snapshot”. Also, instead of a button opening a model, maybe there should instead be a new Customizer section positioned at the top for managing Snapshots, similar to Settings Revisions: https://wordpress.org/plugins/settings-revisions/screenshots/

This could provide opportunities for adding UI for loading an existing snapshot.
