### ISSUE TITLE
Allow settings to be deleted from a snapshot

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-snapshots#17]
Given a UI for listing out the available snapshots in the WP Admin (#12), if opening a snapshot in its edit post screen (see also #16), there could be a listing of the settings in that snapshot along with checkboxes that when checked, a button could be clicked to remove them from the snapshot.

**Comment by westonruter** [comment]
Likewise, when calling `$snapshot->set( $setting_id, null )` this should have the effect of removing the setting from the snapshot.

**Comment by valendesigns** [comment]
That isn't really needed in wp-admin. I envisioned creating a backbone collection of the setting IDs and using buttons to remove and undo. The buttons would modified the collection and dynamically update a hidden input. That way when "Save Draft" is clicked the new content is updated without those IDs.

**Comment by westonruter** [comment]
@valendesigns OK, so you're thinking to not do this the WP admin edit post screen, but rather inside the Customizer itself? I think this ties into that idea we had about providing a UI to list out what the current pending changes are in the Customizer. When loading the Customizer with a snapshot, we'd need to grab all of the setting values prior to calling `preview` and then export them to JS; we likewise have the original setting values in `wp.customize.settings.settings`. Then in the UI for showing the dirty settings, all that we'd need to do is have a button listed with each setting that says “revert” and the behavior would be to override the setting's value to be whatever the original/non-snapshotted value was, and then set `_dirty` to `false`. 

The trick then would be if the user updates the snapshot, we'd also need to send a list of all of the settings that have been reverted so that when the snapshot is saved, those settings can be removed from it. This was what I was referring to with `null`. If reverted settings persist in the settings that are sent to the server when updating the snapshot, but instead of being the actual (when they are dirty) value we send `null` instead, this can be a way to indicate that the setting should be dropped from the snapshot.

**Comment by valendesigns** [comment]
No, I think you misunderstood me, we're talking about two different pieces of the puzzle. I'm saying that we don't need to bootstrap the Customizer in `wp-admin` and use the `CustomizeSnapshots::set()` method to remove settings by supplying a `null` value. Instead we filter the `post_content` during save to unset the IDs we want removed.

What you mentioned above still is valid if we want to revert settings in the Customizer, but that is low priority IMO.

**Comment by kienstra** [comment]
**Pull Request Opened**

Hi @westonruter,
Could you please review this [pull request](https://github.com/xwp/wp-customize-snapshots/pull/84/files)? 
- [73c5b28](https://github.com/xwp/wp-customize-snapshots/commit/73c5b28201f8f951f8c3e938405486cfb6f9a40e) : [Create link](https://github.com/xwp/wp-customize-snapshots/compare/feature/allow-deleting-settings?expand=1#diff-36a80da8dbba0bdbe840617270bb1182R365) `'Remove setting'`, which toggles to `'Restore setting'` [on click](https://github.com/xwp/wp-customize-snapshots/compare/feature/allow-deleting-settings?expand=1#diff-19c3ccdc306cf3ee7efd933155ccae35R18).
  It also [sets a hidden input field](https://github.com/xwp/wp-customize-snapshots/compare/feature/allow-deleting-settings?expand=1#diff-19c3ccdc306cf3ee7efd933155ccae35R40) for each setting to be removed.
  On saving, these appear in `$_REQUEST[ 'customize_snapshot_remove_settings' ]`.
  Filter post content  [on content_save_pre](https://github.com/xwp/wp-customize-snapshots/compare/feature/allow-deleting-settings?expand=1#diff-36a80da8dbba0bdbe840617270bb1182R117) when this is saved.
  If `$_REQUEST` has settings to be removed, [filter them out](https://github.com/xwp/wp-customize-snapshots/compare/feature/allow-deleting-settings?expand=1#diff-36a80da8dbba0bdbe840617270bb1182R722).
  Also, add [simple styling](https://github.com/xwp/wp-customize-snapshots/compare/feature/allow-deleting-settings?expand=1#diff-96bf05ff71d50822b5e71fea81a765e1R1) of this 'Remove setting' link.
  It [appears red](https://github.com/xwp/wp-customize-snapshots/compare/feature/allow-deleting-settings?expand=1#diff-96bf05ff71d50822b5e71fea81a765e1R4) when it has the text "Remove setting, and blue otherwise.
